version: '3'
services:
  dtback:
    image: kapitanmf/tomcat8planogram:08.09.2020
    restart: always
    networks:
      - local
    ports:
      - 8084:8080 
      - 8501:8501
    environment: 
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8501"
  dtfront:
    image: kapitanmf/nginx:1.19.timezonekiev2.7
    restart: always
    ports:
      - 8085:80
    networks:
      - local
    volumes:
      - /docker/planogram/ang:/usr/share/nginx/html

networks:
  local:
    external:
      name: br0
