version: '2'
services:
  pim:
    image: kapitanmf/tomcat8pim:31.08.2020.1
    logging:
      options:
        max-size: "100m"   
    restart: always
    ports:
      - 8082:8080
                       