version: '2'
services:
  pim:
    image: kapitanmf/tomcat8pim:04.09.2020newpostgres
    #image: kapitanmf/tomcat8pim:01.09.2020
    logging:
      options:
        max-size: "100m"
    restart: always
    ports:
      - 8082:8080
      - 8500:8500
    environment: 
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8500"
    networks:
      - local

networks:
  local:
    external:
      name: br0